### PR TITLE
Node-agent: Fix the pre and post run atoms of import cluster flow.

### PR DESCRIPTION
**Pull request by nnDarshan**
This patch fixes the pre atom "compare" and the post atom
"chech_cluster_id_exists" of the import cluster flow.

Issue #71

Signed-off-by: nnDarshan <darshan.n.2024@gmail.com>

### CODE REVIEW

**Comment by nnDarshan** [comment]
@nthomas-redhat @shtripat @r0h4n

**Comment by brainfunked** [comment]
At worst, this code needs to go into commons. Being able to check if a cluster id exists or not is an essential library method. This should not be part of the node agent codebase.

Secondly, this should be turned into a specification for framework enhancement before committing the code for it.

Value comparison, validations, checks for specific keys in etcd etc. needs to be part of the commons library. Generic methods that provide such functionality should be in commons. The inputs themselves should be picked up from the flow global variables, and the library atoms should invoked with these inputs via the flow files. This means that the flow files also need to support inputs to be provided to the atoms.

@nnDarshan @shtripat please turn this into a specification this week. Make a pull request on the specifications repository and we can review and expand the specification there.

**Comment by shtripat** [comment]
@brainfunked https://tendrl.atlassian.net/browse/TEN-157 has listed various common module refactor stuff.
Can you please create required github issues and assign to respective people?

**Comment by brainfunked** [comment]
@shtripat Can't create issues till there's a specification. We'll link the specification to that jira issue. The github issues will be created based on the specification.

**Pull request closed without merging**
